### ISSUE TITLE
Yang-Explorer database is not initialized

### ISSUE THREAD

**Issue by the-wolfox** [CiscoDevNet/yang-explorer#120]
hello, I'm new to linux and I'm getting this error when try to launch yang-explorer : 
`Yang-Explorer database is not initialized .. please run setup.sh first !!`

I installed python2.7, created an V-environment using : 
`virtualenv -p /usr/bin/python2.7 yang-exp`, activated it and executed setup.bsh . 

I also tried to do the same without the activating the env , but the problem persist

**Comment by acodens** [comment]
You are on the right path, Yang-Explorer was built using Python2, I spend myself quite a bit of time trying to run it using Python3 but it never worked, I got the same error as you did no matter how many times I tried to reinstall it.

After a while I made it work, and this is what I did: 
1) Make sure you install all the recommended dependencies as follow:
    python,  python-dev,  zlib1g-dev,  libxml2-dev,  libxslt1-dev,  graphviz
2) pip install --upgrade pip, pip install --upgrade setuptools
3) pip install pyang
4) Use python 2.x

Have in mind the following: 
- Go to your yang-explorer folder and do cat start.sh
- Go to this section: echo "Setting up initial database .."
     -- In this section the bash script is going to create the necessary directories like: users, session, collections and annotation. 
     -- Django Models are used: python manage.py migrate and python manage.py setupdb

- You can run these commands by yourself under the server folder, you don't need to run the setup.sh again and again... 

cd server/
        mkdir -p data/users
        mkdir -p data/session
        mkdir -p data/collections
        mkdir -p data/annotation
python manage.py migrate
python manage.py setupdb

The outputs from here helped me to find my issue. 

Good luck, let me know if this was helpful for you.

**Comment by the-wolfox** [comment]
Hey , tank you for the answer but I figured it out. I used docker with a pre-build image (I guess this is what it's used for; compatibility issues ). Man this software is good especially for learning, but eugh... pyhton2 pip2 flash
