### ISSUE TITLE
Improvement: configurable timeout in device settings

### ISSUE THREAD

**Issue by wisotzky** [CiscoDevNet/yang-explorer#23]
The current implementation is using a fixed timeout of 30seconds. If the ncclient backend has not finished processing a NETCONF request within that time, the user will get an HTTP timeout via the web frontend.

In the specific case, there was some latency between the NETCONF server and the PyangExplorer (double VPN). Also it seems that ncclient is running in debug mode which cost a lot of performance. In my case it was necessary to change the code in utils/runner.py (line 98) to 120 seconds. Please keep in mind, that fetching a complete configuration will take time (based on size of the configuration in MByte).

**Comment by pgohite** [comment]
Thanks for opening issue.. Yes, we can make this configurable. Will fix.
