### ISSUE TITLE
How to restart yang explorer server properly?

### ISSUE THREAD

**Issue by hellt** [CiscoDevNet/yang-explorer#24]
Hello,
I managed to add some models first time. Next week I tried to delete some and got `something went wrong, returned errored response`
How to see what is wrong and properly restart the server to see if it helps?

**Comment by pgohite** [comment]
Hi, Hope you were able to solve the issue. Debugs are by default disabled now but you can enable  them by uncommenting line 40 in yang-explorer/server/explorer/views.py.

**Comment by hellt** [comment]
@pgohite thanks for the hint. Will do next time if I see the same error.
