### ISSUE TITLE
Installation failed !! aborted !!

### ISSUE THREAD

**Issue by rkumcs** [CiscoDevNet/yang-explorer#32]
Hi,

want to install yang-explorer as first time user on a MAC. Did start the installation with sudo -H bash setup.sh. 

At some point installation failed:

Collecting ncclient==0.4.7 (from -r requirements.txt (line 12))
  Using cached ncclient-0.4.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-5kl0lt6t/ncclient/setup.py", line 24
        print "Sorry, Python 3 is not supported (yet)"
                                                     ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-5kl0lt6t/ncclient/
Installation failed !! aborted !!

I do have python 2.7.10 and 3.5.1 running. Paython 2.7.10 is default. Any tipp ?

Ralf

**Comment by miott** [comment]
You may be able to edit setup.sh

 53 else

 54     virtualenv v

 55     source v/bin/activate

 56 fi


First find the path to 2.7 python

bash-3.2$ which python

/Library/Frameworks/Python.framework/Versions/2.7/bin/python

bash-3.2$ ls /Library/Frameworks/Python.framework/Versions/

2.7 3.4 Current

bash-3.2$


Change line 53 to this

virtualenv -p <full path to 2.7 python> v


In my example it would be:

 53 else

 54     virtualenv -p /Library/Frameworks/Python.framework/Versions/2.7 v

 55     source v/bin/activate

 56 fi

Michael

**Comment by pgohite** [comment]
Also, if possible please avoid using sudo with setup.sh

**Comment by pgohite** [comment]
Hope this issue is solved.
