### ISSUE TITLE
Flash player on Linux

### ISSUE THREAD

**Issue by snmpboy** [CiscoDevNet/yang-explorer#35]
The Django app looks for flash version 16.0.0 but the latest flash player on Adobe's site for Linux is 11.2.  Therefore, all attempts to start the app fail and tell  you to download the latest Adobe flash player.  Can you disable that version check?
Thanks,

Mitch

**Comment by pgohite** [comment]
Hi Mitch,

Please use chrome for linux. It has compatible version of flash. 

https://www.google.com/chrome/browser/desktop/

Thanks,
Pravin

**Comment by snmpboy** [comment]
looks like it's for a debian variant not a RedHat variant.

Mitch

Date: Mon, 29 Aug 2016 11:07:51 -0700

**Comment by snmpboy** [comment]
Oops... disregard.  there is an RPM version there.

Mitch

Date: Mon, 29 Aug 2016 11:07:51 -0700

**Comment by snmpboy** [comment]
Google has eliminated support for Chrome on CentOS/RHEL 6..x.  Workaround here: http://www.tecmint.com/install-google-chrome-on-redhat-centos-fedora-linux/

Mitch

Date: Mon, 29 Aug 2016 11:07:51 -0700
