### ISSUE TITLE
Failed to build lxml during install on Ubuntu 16.04.1 LTS

### ISSUE THREAD

**Issue by NathanDotTo** [CiscoDevNet/yang-explorer#36]
Failed to build lxml
Installing collected packages: Django, ecdsa, pycrypto, paramiko, requests, markupsafe, Jinja2, Unidecode, python-slugify, sqlparse, django-debug-toolbar, lxml, graphviz, ncclient, pyang
  Running setup.py install for lxml ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3n0oBg/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-q4GDKX-record/install-record.txt --single-version-externally-managed --compile:
    Building lxml version 3.4.4.
    Building without Cython.
    ERROR: /bin/sh: 1: xslt-config: not found
    
    ** make sure the development packages of libxml2 and libxslt are installed **

Solved with:

sudo apt-get -y install libxml2-dev libxslt-dev

**Comment by pgohite** [comment]
Thanks. Instructions to install these libraries are provided in README, installation section.
