### ISSUE TITLE
No device profile showing 

### ISSUE THREAD

**Issue by NathanDotTo** [CiscoDevNet/yang-explorer#37]
Hi

I am running yang-explorer on Ubuntu 16.04 LTS.

I am trying to use it with Chrome on OS X 10.11.6 and Ubuntu 16.04 LTS.

I have created a device profile, but I am unable to select that device profile.

Please see attached images.

Many thanks

Nathan
![no_device_profile](https://cloud.githubusercontent.com/assets/13392790/18160921/e33ca256-702f-11e6-9a7f-120bab63c6c3.png)
![device_profile_1](https://cloud.githubusercontent.com/assets/13392790/18161007/54981e1c-7030-11e6-9733-3ce4cdf4a42a.png)
![device_profile_2](https://cloud.githubusercontent.com/assets/13392790/18161008/54b8a6a0-7030-11e6-8773-f3e7e18ca2cb.png)
![chrome_flash](https://cloud.githubusercontent.com/assets/13392790/18161014/596de21e-7030-11e6-91bd-4e53896d79a7.png)

**Comment by pgohite** [comment]
It appears that device profile was added for user 'admin' and you might be logged in as 'guest' in yang-explorer. You can update device profile to change 'User:' field or Check 'Shared Device'.

**Comment by pgohite** [comment]
Hope this issue is solved with previous solution. Please reopen the issue if you still see it.
