### ISSUE TITLE
to upload juniper yang failed

### ISSUE THREAD

**Issue by vincenzheng** [CiscoDevNet/yang-explorer#47]
hello, I tried to use this to upload juniper yang as well, but it failed:

python manage.py bulkupload --user admin --git https://github.com/Juniper/yang.git --dir 14.2

So it's only for Cisco YANG? 

Git upload ..
Cloning into '/vagrant/yang-explorer-master/server/data/session/tmpasKAaI'...
remote: Counting objects: 19, done.
remote: Total 19 (delta 0), reused 0 (delta 0), pack-reused 19
Unpacking objects: 100% (19/19), done.
Checking connectivity... done.
Cleaning up /vagrant/yang-explorer-master/server/data/session/tmpasKAaI
Compiling : user: admin, file: /vagrant/yang-explorer-master/server/data/session/tmpDK7KBB/configuration.yang
DEBUG:root:Compiling session dependency ...
/usr/local/bin/pyang
DEBUG:root:Rebuilding dependencies for user admin
['pyang', '-f', 'pyimport', '--plugindir', 'explorer/plugins', '-p', 'data/users/admin/yang:data/session/tmpDK7KBB', 'data/session/tmpDK7KBB/configuration.yang']
DEBUG:root:invoke_compile: CMD: ['pyang', '-f', 'pyimport', '--plugindir', 'explorer/plugins', '-p', 'data/users/admin/yang:data/session/tmpDK7KBB', 'data/session/tmpDK7KBB/configuration.yang']
ERROR:root:invoke_compile: Compile Errors: []
Compilation Failed: <messages/>
Cleaning up /vagrant/yang-explorer-master/server/data/session/tmpDK7KBB
vagrant@vagrant-ubuntu-trusty-64:/vagrant/yang-explorer-master/server$

**Comment by pgohite** [comment]
It should work with any standard yang model. As your model is big, It might need extra memory during compilation. Try increasing memory for you vm.

**Comment by vincenzheng** [comment]
not good. I tried with memory  more than 8G. still not working.

**Comment by vincenzheng** [comment]
Thank you for your quick response.  pgohite. Would you explain how to compile model manually?

I tried with following command  manually and it looks there's 'Segmentation fault' raised.   

(v)vagrant@vagrant-ubuntu-trusty-64:~/yang-explorer/server$ pyang -f pyimport --plugindir explorer/plugins -p data/users/admin/yang:/home/vagrant /home/vagrant/configuration.yang
Segmentation fault (core dumped)

**Comment by vincenzheng** [comment]
solved it after reinstallation. thanks

**Comment by pgohite** [comment]
Thanks
