### ISSUE TITLE
issue in runner.py 

### ISSUE THREAD

**Issue by vincenzheng** [CiscoDevNet/yang-explorer#48]
I found I need to change the 'def run '  in runner.py  to make it working  for juniper device.

all the 'response = xxxxxx.xml'   has to be changed to xxxxx.data_xml , for example like the following  to make it working:
response = self.handle.get(data).data_xml

otherwise there's error message:

```
response = self.handle.get(data).xml
```

AttributeError: 'NCElement' object has no attribute 'xml'

**Comment by pgohite** [comment]
Thanks for reporting, there may have been some changes in ncclient, I'll verify and fix.

**Comment by vincenzheng** [comment]
Hi, pgohite,

Forgive me I am not  familiar with web side,  I am just wondering if  the WSGIrequest  was created from web side, is that right?   I mean it's created from adobe swf ? or  is there any python code related to create this?

thanks.
