### ISSUE TITLE
failed to create correct junos restconf rpc

### ISSUE THREAD

**Issue by vincenzheng** [CiscoDevNet/yang-explorer#49]
the junos restconf rpc it created is not correct, for example, for get interface configration, it created the url:
"url": "/restconf/api/running/configuration/interfaces/interface".

actually, it looks something like this:
curl http://ip:port/rpc/get-interface-information -u "xxx:yyyy" -H "Content-Type: application/xml" -H "Accept: application/xml"

Do you know where to change the code to  create the correct restconf?   is it done on the web browser side?

**Comment by pgohite** [comment]
Please note that restconf support is experimental in yang-explorer, it need to be refactored once restconf draft becomes a RFC. 

All RPCs are generated by server code, located in server/explorer/utils/restconf.py

It seems that your RPC in curl command is not based on config model you have loaded hence it can not generate correct path.
