### ISSUE TITLE
Are some yang models unsubscriptable?

### ISSUE THREAD

**Issue by hellt** [CiscoDevNet/yang-explorer#51]
Hi,
Is it ok that I cant subscribe to some models? For example to bundled `ietf-inet-types` and some others? Clicking on `Subscribe` just has no effect on these models. Logs (debug is not active) shows nothing strange, I receive some `200 OK` response.

**Comment by einarnn** [comment]
Models like ```ietf-inet-types``` do not have any data nodes, so you won't see anything when you subscribe to them. They are dependencies of other modules, and will thus be imported by those other models as required.

**Comment by hellt** [comment]
Thanks for explanation.
Should it be indicated somehow, maybe in a status bar or with popup? Because now for yang-newbies it feels like smth is not working. Just suggesting...
