### ISSUE TITLE
Installation behind a proxy

### ISSUE THREAD

**Issue by yelfathi** [CiscoDevNet/yang-explorer#54]
On ubuntu and behind a proxy I had to edit the setup.sh to add proxy information at this line:

```
echo "Installing dependencies .."
pip install **--proxy=http://my.proxy.com:8080** -r requirements.txt
```

You can add an option in the bash script to allow the user to provide a proxy.

**Comment by robertcsapo** [comment]
You could use environment variables in your session
```
export http_proxy="http://<proxy.server>:<port>"
```
as pip honors http_proxy/https_proxy environment variables

**Comment by yelfathi** [comment]
I tried it before but did not work, maybe a typo in my env variable value!
