### ISSUE TITLE
Cannot upload some yang modules

### ISSUE THREAD

**Issue by jean-christophe-manciot** [CiscoDevNet/yang-explorer#60]
Login as guest
Manage Models -> Workspace -> Add -> Browse -> Select some Yang Modules -> OK -> Upload leads to:
![yang-explorer - uploading yang models](https://cloud.githubusercontent.com/assets/13176858/25041949/5e1b9f46-2114-11e7-8a1f-3d93a42328de.jpg)

**Comment by jean-christophe-manciot** [comment]
The trace from CLI is:
```
[14/Apr/2017 11:56:23]"GET /static/YangExplorer.html HTTP/1.1" 200 6622
[14/Apr/2017 11:56:23]"GET /static/YangExplorer.html HTTP/1.1" 200 6622
[14/Apr/2017 11:56:24] WARNING [django.request] Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
[14/Apr/2017 11:56:24]"GET /favicon.ico HTTP/1.1" 404 2546
[14/Apr/2017 11:56:24]"GET /static/history/history.css HTTP/1.1" 304 0
[14/Apr/2017 11:56:24]"GET /static/history/history.js HTTP/1.1" 304 0
- Broken pipe from ('127.0.0.1', 35512)
[14/Apr/2017 11:56:24]"GET /static/swfobject.js HTTP/1.1" 304 0
[14/Apr/2017 11:56:24]"GET /static/YangExplorer000700.swf HTTP/1.1" 304 0
[14/Apr/2017 11:56:26]"GET /explorer/session HTTP/1.1" 200 97
[14/Apr/2017 11:56:35]"POST /explorer/login HTTP/1.1" 200 343
INFO:explorer.views:Received admin request modulelist for user guest
INFO:explorer.views:request_handler: Received Request: (get-collection-list)
[14/Apr/2017 11:56:35]"GET /explorer/userprofiles HTTP/1.1" 200 121
[14/Apr/2017 11:56:35]"GET /explorer/netconf?mode=get%2Dcollection%2Dlist HTTP/1.1" 200 83
INFO:explorer.utils.admin:ModuleAdmin.get_modules: returning (5) modules .. exit
[14/Apr/2017 11:56:35]"GET /explorer/admin?action=modulelist HTTP/1.1" 200 344
[14/Apr/2017 11:56:35]"GET /explorer/modules?node=root HTTP/1.1" 200 348
ERROR:root:Session storage data/session/jsqc46setdw8m16i8pnwrelh42djirf5 does not exist
[14/Apr/2017 11:56:41]"GET /explorer/upload?mode=init HTTP/1.1" 200 64
WARNING:explorer.views:User must be logged in !!
[14/Apr/2017 11:57:21]"POST /explorer/upload/upload-add HTTP/1.1" 200 48
```

**Comment by jean-christophe-manciot** [comment]
The documentation says:
```
###4. Caveats
Yang Model upload fails, Workaround: Use Google Chrome.
```
Problem: **chrome does not work as it does not support flash anymore**:
```
To view this page ensure that Adobe Flash Player version 16.0.0 or greater is installed.
```

**Comment by jean-christophe-manciot** [comment]
I feel like speaking in a ghost town.

**Comment by rustogi** [comment]
Jean-Christophe,

I tried the following version (latest) of chrome on Mac OS X and didn't have any issues. Need your help in reproducing it.

The version of chrome I am using - Version 58.0.3029.96 (64-bit)

Could you indicate your chrome browser version.

Here are the steps I used to reproduce this. Are you following the same steps or are they different, if so could you indicate the differences.

```
bash setup.sh
./start.sh

$ ./start.sh 

Activating virtualenv ..
Starting YangExplorer server ..
Use http://0.0.0.0:8090/static/YangExplorer.html

Performing system checks...

System check identified no issues (0 silenced).
May 06, 2017 - 13:50:26
Django version 1.8.3, using settings 'server.settings'
Starting development server at http://0.0.0.0:8090/
Quit the server with CONTROL-C.

```
Then go to http://localhost:8088/static/YangExplorer.html in google chrome.

```
[06/May/2017 13:50:44]"GET /explorer/session HTTP/1.1" 200 345
[06/May/2017 13:50:44]"GET /explorer/userprofiles HTTP/1.1" 200 121
INFO:explorer.views:Received admin request modulelist for user guest
INFO:explorer.utils.admin:ModuleAdmin.get_modules: returning (6) modules .. exit
[06/May/2017 13:50:44]"GET /explorer/admin?action=modulelist HTTP/1.1" 200 370
INFO:explorer.views:request_handler: Received Request: (get-collection-list)
[06/May/2017 13:50:44]"GET /explorer/modules?node=root HTTP/1.1" 200 205
[06/May/2017 13:50:44]"GET /explorer/netconf?mode=get%2Dcollection%2Dlist HTTP/1.1" 200 83
```


Then click on 'guest' tab and login as guest/guest

```
[06/May/2017 13:52:28]"POST /explorer/login HTTP/1.1" 200 96
[06/May/2017 13:52:45]"POST /explorer/login HTTP/1.1" 200 343
[06/May/2017 13:52:45]"GET /explorer/userprofiles HTTP/1.1" 200 121
[06/May/2017 13:52:45]"GET /explorer/modules?node=root HTTP/1.1" 200 205
INFO:explorer.views:request_handler: Received Request: (get-collection-list)
[06/May/2017 13:52:45]"GET /explorer/netconf?mode=get%2Dcollection%2Dlist HTTP/1.1" 200 83
INFO:explorer.views:Received admin request modulelist for user guest
INFO:explorer.utils.admin:ModuleAdmin.get_modules: returning (6) modules .. exit
[06/May/2017 13:52:45]"GET /explorer/admin?action=modulelist HTTP/1.1" 200 370
```

Then click on 'Manage Models', 'Workspace', and 'Add'.

```
ERROR:root:Session storage data/session/ocnu5swfy4uj12q4na0t8xag58wjq5rh does not exist
[06/May/2017 13:54:09]"GET /explorer/upload?mode=init HTTP/1.1" 200 64
```

Then 'Browse' and 'Upload' and that worked for me.

```
[06/May/2017 13:58:49]"POST /explorer/upload/upload-add HTTP/1.1" 200 100
INFO:explorer.views:Received sync request for ietf-system@2014-08-06.yang, index 0
/home/vagrant/yang/bugs/yang-explorer/v/bin/pyang
/home/vagrant/yang/bugs/yang-explorer/v/bin/pyang
WARNING:root:Dependent modules ietf-netconf-acm not found in dependency list !!
WARNING:root:Dependent modules iana-crypt-hash not found in dependency list !!
WARNING:root:get_dependencies: Dependency (ietf-inet-types) not satisfied, compilation may fail !!
WARNING:root:get_dependencies: Dependency (ietf-yang-types) not satisfied, compilation may fail !!
WARNING:root:get_dependencies: Dependency (ietf-netconf-acm) not satisfied, compilation may fail !!
WARNING:root:get_dependencies: Dependency (iana-crypt-hash) not satisfied, compilation may fail !!
[06/May/2017 13:58:49]"GET /explorer/upload?index=0&file=ietf%2Dsystem%402014%2D08%2D06%2Eyang&mode=sync HTTP/1.1" 200 54
WARNING:root:Dependent modules ietf-netconf-acm not found in dependency list !!
WARNING:root:Dependent modules iana-crypt-hash not found in dependency list !!
WARNING:root:get_dependencies: Dependency (ietf-netconf-acm) not satisfied, compilation may fail !!
WARNING:root:get_dependencies: Dependency (iana-crypt-hash) not satisfied, compilation may fail !!
[06/May/2017 13:58:50]"GET /explorer/upload?mode=commit HTTP/1.1" 200 119
INFO:explorer.views:Received admin request modulelist for user guest
INFO:explorer.utils.admin:ModuleAdmin.get_modules: returning (6) modules .. exit
[06/May/2017 13:58:50]"GET /explorer/admin?action=modulelist HTTP/1.1" 200 370
[06/May/2017 13:58:50]"GET /explorer/modules?node=root HTTP/1.1" 200 205
```

**Comment by jean-christophe-manciot** [comment]
Please read previous post [here](https://github.com/CiscoDevNet/yang-explorer/issues/60#issuecomment-299506380).
I was forced to use latest Firefox 53.0 (64-bit) on **Linux 4.8 Ubuntu 16.10**

**Comment by jean-christophe-manciot** [comment]
I cannot see any 'guest' tab per say, just a login box:
![no guest tab](https://cloud.githubusercontent.com/assets/13176858/25856412/3081682e-34d6-11e7-8970-20627a1b9ddb.jpg)
When logged in as guest/guest:
![logged in](https://cloud.githubusercontent.com/assets/13176858/25856686/0f0052c2-34d7-11e7-9251-beb15a3b4643.jpg)
and try to upload the modules, I get the first same error as you, which you have silently ignored:
```
ERROR:root:Session storage data/session/88xct034q5tb0ld0v9jfqwi95o3n7y5v does not exist
```
and then the guest user is not seen:
![not logged in](https://cloud.githubusercontent.com/assets/13176858/25856783/4ddb7a58-34d7-11e7-9e4f-36b6607af65d.jpg)

```
[09/May/2017 14:41:46]"GET /explorer/upload?mode=init HTTP/1.1" 200 64
WARNING:explorer.views:User must be logged in !!
[09/May/2017 14:43:50]"POST /explorer/upload/upload-add HTTP/1.1" 200 48
```

**Comment by rustogi** [comment]
@jean-christophe-manciot 

Regarding your comment "Please read previous post here." <---- This is pointing back at this post itself where you mention

"Problem: chrome does not work with yang explorer as it does not support flash anymore"

But I am able to use the chrome version (which I indicated above) fine and it does support flash. Could you point me to what error were you seeing with chrome? And also indicate your chrome version.

As for your comment "Hence, I was forced to use latest Firefox 53.0 (64-bit) on Linux 4.8 Ubuntu 16.10", since we support Chrome currently, I want to first debug this with chrome, if possible.

As for the error "ERROR:root:Session storage data/session/88xct034q5tb0ld0v9jfqwi95o3n7y5v does not exist" this is harmless and can be ignored. I see it too and it does not cause any issues.

Agree with your observation that the tab should be "Login" not "Guest" - my bad - I will fix the typo.

Also would really appreciate it if you could follow the same template I provided above (in me earlier response on this thread), from starting the yang explorer and then capture server side logs for each of the different operations/key presses on the browser side. This will allow me to see the entire progression of messages to debug this. I apologize for asking this, but as I mentioned I am not seeing this issue so first trying to reproduce it.

**Comment by jean-christophe-manciot** [comment]
> But I am able to use the chrome version
Not on Ubuntu

**Comment by jean-christophe-manciot** [comment]
OK, my chrome was not setup correctly on Ubuntu, so you can dismiss my remarks about it.
I am now able to upload some [official openconfig models](https://github.com/openconfig/public), but:
1) **some fail**
![some fail to upload](https://cloud.githubusercontent.com/assets/13176858/25891210/7a1bc2a0-3570-11e7-906b-83b2292e0e32.jpg)
2) it is very **cumbersome** to use because 
    a) it is not possible to recursively upload a folder
    b) we have to close the "upload yang" window each time to upload another group of models
![one upload done](https://cloud.githubusercontent.com/assets/13176858/25891249/a4339f90-3570-11e7-9730-a4c5c2fdf460.jpg)
3) once a group of yang files have been uploaded, they are **nowhere to be found on the GUI**
![nowhere to be found](https://cloud.githubusercontent.com/assets/13176858/25891259/aaf20998-3570-11e7-828d-bf56345b6a9d.jpg)

**Comment by rustogi** [comment]
Ok Tx for verifying the chrome issue. I will try and reproduce the other issue you mentioned wrt uploading models and update this thread accordingly.

**Comment by jean-christophe-manciot** [comment]
@rustogi 
Trying to upload the **Cisco yang models** available on https://github.com/YangModels/yang in vendor/cisco/**xe/1641** triggers **a lot of warnings and errors**:
```
data/session/8cftfs9u07ok0ihcw1bl1cza8hvrqt3m/cisco-flow-monitor@2015-10-26.yang:8: warning: imported module tailf-common not used
data/session/8cftfs9u07ok0ihcw1bl1cza8hvrqt3m/cisco-qos-action-marking-cfg@2015-05-09.yang:23: warning: imported module ietf-diffserv-action not used
data/session/8cftfs9u07ok0ihcw1bl1cza8hvrqt3m/cisco-qos-action-qlimit-cfg@2015-05-09.yang:19: warning: imported module ietf-diffserv-policy not used
data/session/8cftfs9u07ok0ihcw1bl1cza8hvrqt3m/cisco-qos-action-qlimit-cfg@2015-05-09.yang:23: warning: imported module ietf-diffserv-action not used
data/session/8cftfs9u07ok0ihcw1bl1cza8hvrqt3m/ned@2016-10-24.yang:63067: warning: locally scoped grouping pfr-border-grouping not used
data/session/8cftfs9u07ok0ihcw1bl1cza8hvrqt3m/openconfig-aft-network-instance@2017-01-13.yang:8: error: module "openconfig-network-instance" not found in search path
data/session/8cftfs9u07ok0ihcw1bl1cza8hvrqt3m/openconfig-aft@2017-01-13.yang:13: error: module "openconfig-mpls-types" not found in search path
data/session/8cftfs9u07ok0ihcw1bl1cza8hvrqt3m/openconfig-aft@2017-01-13.yang:14: error: module "openconfig-interfaces" not found in search path
data/session/8cftfs9u07ok0ihcw1bl1cza8hvrqt3m/openconfig-aft@2017-01-13.yang:16: error: module "openconfig-policy-types" not found in search path
data/session/8cftfs9u07ok0ihcw1bl1cza8hvrqt3m/openconfig-bgp-common@2017-02-02.yang:9: error: module "openconfig-routing-policy" not found in search path
data/session/8cftfs9u07ok0ihcw1bl1cza8hvrqt3m/openconfig-bgp-global@2017-02-02.yang:7: error: module "openconfig-extensions" not found in search path
data/session/8cftfs9u07ok0ihcw1bl1cza8hvrqt3m/openconfig-bgp-global@2017-02-02.yang:8: error: module "openconfig-yang-types" not found in search path
data/session/8cftfs9u07ok0ihcw1bl1cza8hvrqt3m/openconfig-bgp-global@2017-02-02.yang:9: error: module "openconfig-inet-types" not found in search path
data/session/8cftfs9u07ok0ihcw1bl1cza8hvrqt3m/openconfig-bgp-types@2017-02-02.yang:8: error: module "openconfig-types" not found in search path
data/session/8cftfs9u07ok0ihcw1bl1cza8hvrqt3m/pim@2014-06-27.yang:7: warning: imported module ietf-inet-types not used
data/session/8cftfs9u07ok0ihcw1bl1cza8hvrqt3m/pim@2014-06-27.yang:8: warning: imported module ietf-yang-types not used
data/session/8cftfs9u07ok0ihcw1bl1cza8hvrqt3m/pim@2014-06-27.yang:9: warning: imported module ietf-interfaces not used
```
This reminds me of another issue previously discussed with @einarnn [here](https://github.com/YangModels/yang/issues/139).

**Comment by jean-christophe-manciot** [comment]
When I take a look at yang-explorer/requirements.txt, I notice:
- **lxml==3.4.4**: this is precisely the dependency explaining most warnings and errors according to @einarnn 
- **pyang==1.6.0**: is there a reason why you're putting a strong version constraint instead of using the latest (1.7.1) with >=1.6.0?

**Comment by rustogi** [comment]
@jean-christophe-manciot I will let @einarnn respond to your questions regarding warnings and errors you are seeing as generated by pyang tool.

As for your previous comment regarding recursively loading models from sub-directories under the top level directory, the way I do that is once I click the "Browse" button, I am asked to pick the local directory under which my .yang files exist. Then I block select all models (.yang files)  under that directory and then click "Upload". Once I do that , all those models are uploaded. As to the compilation issues wrt those models, I will defer to @einarnn.

**Comment by jean-christophe-manciot** [comment]
@rustogi  It does not add up:
- you said you were able to upload some yang models to yang-explorer, although @einarnn explained that lxml dependency triggers a lot of warnings and errors. Lxml is present with yang-explorer by default, so which models have you been able to upload without any error?
- I have to ask my question again: is there a reason why you're putting a strong version constraint instead of using the latest (1.7.1) with >=1.6.0?
- finally, you're missing the point about recursively uploading yang models: try to do this operation with openconfig models and you'll feel the pain. This feature request is about letting people select a **folder** instead of files and **yang-explorer recursively finds all .yang models below that folder**. That's very easy to implement and a big time-saver for users.

**Comment by einarnn** [comment]
Jean-Christophe,

The yang-explorer uses lxml as it's XML parser for dealing with YANG-derived NETCONF payloads. pyang uses lxml (if it's installed) as a library for validating certain aspects of YANG modules (e.g. regular expressions). Thus we unfortunately see that the YANG explorer triggers some errors when pyang is used in the same virtual environment.

A better solution may have been for pyang to be configurable with respect to some parts of validation, rather than how it does it today, which is to perform the validation if lxml just happens to be installed.

Also, it's also interesting to note that even when pyang reports errors, it doesn't necessarily return them in a way that is easily consumed by a client. For example, only some errors return an error that is testable via shell script return code checking. As part of integrating pyang into the Travis CI check for https://github.com/YangModels/yang, see the script at https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/check.sh#L21-L28, which is:

    for f in Cisco-IOS-XR-*-cfg.yang; do
        errors=`pyang $pyang_flags $f 2>&1 | grep "error:"`
        if [ ! -z "$errors" ]; then
            echo Errors in $f
            echo $errors
            exit_status="failed!"
        fi
    done

As you can see, the script has to explicitly check returned output from both stdout and stderr for errors. Thus at this stage I suspect that the yang-explorer currently ignores any error codes from pyang, and as long as a schema tree is available, it works with what it can.

You also ask about the version constraint on pyang. This comes from using the command "pip freeze" to generate dependencies, and is the version that we have tested yang-explorer with. It is entirely possible that pyang 1.7.x will work fine for yang-explorer, but, as yet, we haven't gone through any validation of that.

BTW, I agree about your enhancement suggestion to allow a folder to be specified for recursive upload from a filesystem. @rustogi, I suggest we add that as something to look at. @jean-christophe-manciot, pull requests are also welcome ;-)

Cheers,

Einar

**Comment by rustogi** [comment]
@einarnn @jean-christophe-manciot 
I agree that just allowing a folder would be better. But given the flash dependency of yang-explorer for any gui side changes, the preference would be to make such gui changes in the next (non-flash-based version) of yang explorer gui.

So in the meantime I was just trying to see if with no gui changes we could address @jean-christophe-manciot's use case.

So I created a directory and added some yang models and then added another sub-directory and added more yang models in it and was able to get all yang models uploaded by block selecting models in parent as well as sub-directories, all in one-shot. So just trying to confirm if that is a reasonable workaround till we can address gui changes.

@einarnn please chime is also if this is a reasonable course of action.

@jean-christophe-manciot could you point me to the openconfig directory that I should try this with.

Here is a snapshot of what I had tried.

![screen shot 2017-05-15 at 11 19 55 am](https://cloud.githubusercontent.com/assets/11912458/26064993/94c89170-3960-11e7-94bb-4b7fdaa4ae56.png)

![screen shot 2017-05-15 at 11 20 21 am](https://cloud.githubusercontent.com/assets/11912458/26065004/9af48928-3960-11e7-8b3e-1b8e603c93dd.png)

**Comment by jean-christophe-manciot** [comment]
The official openconfig models are available [here](https://github.com/openconfig/public).
On Ubuntu file manager, you don't have access at what is inside the folders, unless you navigate within them.
Regarding your upload trial, you have bundled a special group of models which is not found anywhere "as such". This bundle does not exist by default on the official [site](https://github.com/YangModels/yang): if you try on a **fresh install** to upload all the models included within, for instance ```yang/vendor/cisco/xr/601```, my guess is the upload will fail.

**Comment by rustogi** [comment]
@jean-christophe-manciot 

Ok I will try these.

**Comment by jean-christophe-manciot** [comment]
@rustogi 
Another example of error when trying to upload on a freshly installed software all default models shipped with yang-explorer from iana (no errors) then ietf (following error) from ```yang-explorer/v/share/yang/modules```:
```
Traceback (most recent call last):
File "/home/actionmystique/Ansible/yang-explorer/v/bin/pyang", line 420, in <module>
run()
File "/home/actionmystique/Ansible/yang-explorer/v/bin/pyang", line 290, in run
expect_failure_error=False)
File "/home/actionmystique/Ansible/yang-explorer/v/local/lib/python2.7/site-packages/pyang/__init__.py", line 100, in add_module
module.i_adler32 = zlib.adler32(text)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 212-214: ordinal not in range(128)
```

**Comment by jean-christophe-manciot** [comment]
It seems that trying to upload a model which has already been uploaded blocks the whole process.

**Comment by jean-christophe-manciot** [comment]
Other models shipped in ```yang-explorer/v/share/yang/modules``` which are not installed by default and trigger the same previous error are:
- ietf-netconf-acm.yang
- ietf-x509-cert-to-name.yang
- ietf-yang-metadata.yang

**Comment by jean-christophe-manciot** [comment]
I was able to finally find a way though the uploading process. Since it does not appear to be documented somewhere, this workaround should interest some users:
- start from a fresh installation
- login as guest/guest
- upload all models inside ```yang-explorer/v/share/yang/modules``` except the ones which are present by default, otherwise the whole process is blocked.
- only then we can upload some [official Cisco models](https://github.com/YangModels/yang) from ```yang-models/vendor/cisco```

**Comment by jean-christophe-manciot** [comment]
I am not able to upload any ```yang-models/vendor/cisco/nx/7.0-3-I5-*``` models: they all fail with error during compilation.

**Comment by ruissalo** [comment]
on  OSX , compilation errors go away if pyang is upgraded to the latest version.

**Comment by jean-christophe-manciot** [comment]
Same compilation errors for NX-OS yang modules 7.0-3-I5-2/7.0-3-I6-1 with pyang 1.7.2 on Linux 4.10.
@ruissalo  What exact modules were you able to compile/upload?

**Comment by ruissalo** [comment]
I was able to upload and compile all Openconfig models.

**Comment by Aileen123456** [comment]
INFO:explorer.views:Received sync request for aaa@2016-01-24.yang, index 0
/opt/home/testmin/Downloads/yang-explorer/v/bin/pyang
ERROR:root:invoke_compile: Compile Errors: ['Traceback (most recent call last):', '  File "/opt/home/testmin/Downloads/yang-explorer/v/bin/pyang", line 420, in <module>', '    run()', '  File "/opt/home/testmin/Downloads/yang-explorer/v/bin/pyang", line 290, in run', '    expect_failure_error=False)', '  File "/opt/home/testmin/Downloads/yang-explorer/v/lib/python2.7/site-packages/pyang/__init__.py", line 100, in add_module', '    module.i_adler32 = zlib.adler32(text)', "UnicodeEncodeError: 'ascii' codec can't encode characters in position 38647-38649: ordinal not in range(128)", '']
[19/Apr/2018 06:22:54]"GET /explorer/upload?mode=sync&index=0&file=aaa%402016%2D01%2D24%2Eyang HTTP/1.1" 200 775

**Comment by Aileen123456** [comment]
![failed](https://user-images.githubusercontent.com/38519908/38974966-9eb5a7e8-43de-11e8-9c35-30ee9a579bc7.PNG)

**Comment by dplore** [comment]
> INFO:explorer.views:Received sync request for [aaa@2016-01-24.yang](mailto:aaa@2016-01-24.yang), index 0
> /opt/home/testmin/Downloads/yang-explorer/v/bin/pyang
> ERROR:root:invoke_compile: Compile Errors: ['Traceback (most recent call last):', ' File "/opt/home/testmin/Downloads/yang-explorer/v/bin/pyang", line 420, in ', ' run()', ' File "/opt/home/testmin/Downloads/yang-explorer/v/bin/pyang", line 290, in run', ' expect_failure_error=False)', ' File "/opt/home/testmin/Downloads/yang-explorer/v/lib/python2.7/site-packages/pyang/**init**.py", line 100, in add_module', ' module.i_adler32 = zlib.adler32(text)', "UnicodeEncodeError: 'ascii' codec can't encode characters in position 38647-38649: ordinal not in range(128)", '']
> [19/Apr/2018 06:22:54]"GET /explorer/upload?mode=sync&index=0&file=aaa%402016%2D01%2D24%2Eyang HTTP/1.1" 200 775

Upgrade to pyang fixed this problem for me,

    pip -U pyang

**Comment by dplore** [comment]
I am 

> Also, it would be so much more efficient to be able to indicate a folder to be recursively searched instead of *.yang models within a single folder.
> If you try to upload all openconfig models, you will feel the pain..

Did you find a solution to upload openconfig modules?  Given the imports between folders, it doesn't seem possible right now.

**Comment by einarnn** [comment]
Easiest solution is to just place all openconfig yang models in a single folder and upload from there.

Cheers,

Einar

**Comment by dplore** [comment]
Thanks, that worked for me!

**Comment by jabelk** [comment]
I had the same issue `UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 4056: ordinal not in range(128)` even after placing all openconfig models in a single folder and pip install upgrading `pyang`. Using chrome on OS X as well. 
```
...
.../yang-explorer/v/lib/python2.7/site-packages/pyang/__init__.py", line 100, in add_module
module.i_adler32 = zlib.adler32(text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 4056: ordinal not in range(128)
```

**Comment by jabelk** [comment]
I have been able to solve my problem by updating the bashrc with `export YANG_MODPATH=$HOME/yang/modules` and putting all the openconfig modules in there with no sub-directories. So when I upload it in the GUI, `pyang` picks up the modules dependent on each other, otherwise was going into dependency hell trying to upload modules.

**Comment by einarnn** [comment]
Glad you have found a workaround!
