### ISSUE TITLE
setup fails to create virtualenv when multiple python2.7 are installed

### ISSUE THREAD

**Issue by matjaz6** [CiscoDevNet/yang-explorer#68]
setup.sh script creates virtualenv. If multiple python interpreters are present on the system this fails. Suggest to use only the first one found, using head or something alike:

-       python_prog=$(type -a python2.7 | cut -d" " -f3)
+       python_prog=$(type -a python2.7 | head -1 | cut -d" " -f3)
        echo "Using Python Program: ${python_prog}"
         virtualenv --python=${python_prog} v

**Comment by rustogi** [comment]
@matjaz6 Agree with your proposed fix. I will work on getting this committed.

**Comment by rustogi** [comment]
Fixed using #75
